"""users to customer changes

Revision ID: 4e91c0ffa3e6
Revises: 78efded12a77
Create Date: 2025-08-17 00:27:12.191342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e91c0ffa3e6'
down_revision: Union[str, None] = '78efded12a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers_table',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('contact_no', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('state', sa.String(length=70), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=70), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('contact_no'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index(op.f('address'), table_name='users_table')
    op.drop_index(op.f('contact_no'), table_name='users_table')
    op.drop_index(op.f('email'), table_name='users_table')
    op.drop_index(op.f('username'), table_name='users_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('contact_no', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('address', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users_table', ['username'], unique=True)
    op.create_index(op.f('email'), 'users_table', ['email'], unique=True)
    op.create_index(op.f('contact_no'), 'users_table', ['contact_no'], unique=True)
    op.create_index(op.f('address'), 'users_table', ['address'], unique=True)
    op.drop_table('customers_table')
    # ### end Alembic commands ###
