"""Added new column is deleted to User

Revision ID: 70b7d8de655a
Revises: 954af892e651
Create Date: 2025-06-14 01:46:01.333345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b7d8de655a'
down_revision: Union[str, None] = '954af892e651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('is_delete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'is_delete')
    # ### end Alembic commands ###
